/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function resolveFontBasic(fontName: string): string
export interface JsSuggestion {
  family: string
  subfamily: string
  source: string
  score: number
  weight: number
  italic: boolean
  isCriticalLicenseWarning: boolean
  licenseName: string
  hasLocalFile: boolean
  downloadUrl?: string
  isOfflineFallback: boolean
}
export interface JsDatabaseStats {
  fontCount: number
  compressedSizeMb: number
  originalSizeMb: number
  compressionRatio: number
}
export interface JsCacheStats {
  memoryEntries: number
  diskEntries: number
  pinnedFonts: number
  memoryUsageMb: number
  diskUsageMb: number
}
export declare function getFontSuggestions(fontName: string, includeInternet: boolean): Promise<Array<JsSuggestion>>
export declare function normalizeFontName(fontName: string): string
export declare function pinFont(fontName: string): void
export declare function unpinFont(fontName: string): void
export declare function removeFromCache(fontNames: Array<string>): number
export declare function exportMetrics(fontName: string): string
export declare function getEngineStats(): JsDatabaseStats
export declare function getCacheStats(): JsCacheStats
export declare function cleanupCache(aggressive: boolean): number
export declare function listPinnedFonts(): Array<string>
export declare function updateDatabase(): Promise<void>
